split up partial pytest

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -817,6 +817,103 @@ jobs:
           . venv/bin/activate
           ./script/pip_check $PIP_CACHE
 
+  partial-pytest:
+    runs-on: ubuntu-22.04
+    if: |
+      (github.event_name != 'push' || github.event.repository.full_name == 'home-assistant/core')
+      && github.event.inputs.lint-only != 'true'
+      && github.event.inputs.pylint-only != 'true'
+      && github.event.inputs.mypy-only != 'true'
+      && (needs.info.outputs.test_partial_suite == 'true')
+    needs:
+      - info
+      - base
+      - gen-requirements-all
+      - hassfest
+      - lint-isort
+      - lint-other
+      - lint-ruff
+      - mypy
+    strategy:
+      fail-fast: false
+      matrix:
+        integration: ${{ fromJson(needs.info.outputs.tests) }}
+        python-version: ${{ fromJson(needs.info.outputs.python_versions) }}
+    name: >-
+      Run tests Python ${{ matrix.python-version }} (${{ matrix.integration }})
+    steps:
+      - name: Install additional OS dependencies
+        run: |
+          sudo apt-get update
+          sudo apt-get -y install \
+            bluez \
+            ffmpeg
+      - name: Check out code from GitHub
+        uses: actions/checkout@v3.3.0
+      - name: Set up Python ${{ matrix.python-version }}
+        id: python
+        uses: actions/setup-python@v4.5.0
+        with:
+          python-version: ${{ matrix.python-version }}
+          check-latest: true
+      - name: Restore full Python ${{ matrix.python-version }} virtual environment
+        id: cache-venv
+        uses: actions/cache/restore@v3.3.0
+        with:
+          path: venv
+          fail-on-cache-miss: true
+          key: ${{ runner.os }}-${{ steps.python.outputs.python-version }}-${{
+            needs.info.outputs.python_cache_key }}
+      - name: Register Python problem matcher
+        run: |
+          echo "::add-matcher::.github/workflows/matchers/python.json"
+      - name: Install Pytest Annotation plugin
+        run: |
+          . venv/bin/activate
+          # Ideally this should be part of our dependencies
+          # However this plugin is fairly new and doesn't run correctly
+          # on a non-GitHub environment.
+          pip install pytest-github-actions-annotate-failures==0.1.3
+      - name: Register pytest slow test problem matcher
+        run: |
+          echo "::add-matcher::.github/workflows/matchers/pytest-slow.json"
+      - name: Compile English translations
+        run: |
+          . venv/bin/activate
+          python3 -m script.translations develop --integration ${{ matrix.integration }}
+      - name: Run pytest (partially)
+        timeout-minutes: 10
+        shell: bash
+        run: |
+          . venv/bin/activate
+          python --version
+
+          if [[ ! -f "tests/components/${{ matrix.integration }}/__init__.py" ]]; then
+            echo "::error:: missing file tests/components/${{ matrix.integration }}/__init__.py"
+            exit 1
+          fi
+
+          python3 -X dev -m pytest \
+            -qq \
+            --timeout=9 \
+            -n auto \
+            --cov="homeassistant.components.${{ matrix.integration }}" \
+            --cov-report=xml \
+            --cov-report=term-missing \
+            -o console_output_style=count \
+            --durations=0 \
+            --durations-min=1 \
+            -p no:sugar \
+            tests/components/${{ matrix.integration }}
+      - name: Upload coverage artifact
+        uses: actions/upload-artifact@v3.1.2
+        with:
+          name: coverage-${{ matrix.python-version }}-${{ matrix.integration }}
+          path: coverage.xml
+      - name: Check dirty
+        run: |
+          ./script/check_dirty
+
   pytest:
     runs-on: ubuntu-22.04
     if: |
@@ -838,7 +935,6 @@ jobs:
       fail-fast: false
       matrix:
         group: ${{ fromJson(needs.info.outputs.test_groups) }}
-        partial_group: ${{ fromJson(needs.info.outputs.tests) }}
         python-version: ${{ fromJson(needs.info.outputs.python_versions) }}
     name: >-
       Run tests Python ${{ matrix.python-version }} (${{ matrix.group }})
@@ -882,31 +978,6 @@ jobs:
         run: |
           . venv/bin/activate
           python3 -m script.translations develop --all
-      - name: Run pytest (partially)
-        if: needs.info.outputs.test_partial_suite == 'true'
-        timeout-minutes: 10
-        shell: bash
-        run: |
-          . venv/bin/activate
-          python --version
-
-          if [[ ! -f "tests/components/${{ matrix.partial_group }}/__init__.py" ]]; then
-            echo "::error:: missing file tests/components/${{ matrix.partial_group }}/__init__.py"
-            exit 1
-          fi
-
-          python3 -X dev -m pytest \
-            -qq \
-            --timeout=9 \
-            -n auto \
-            --cov="homeassistant.components.${{ matrix.partial_group }}" \
-            --cov-report=xml \
-            --cov-report=term-missing \
-            -o console_output_style=count \
-            --durations=0 \
-            --durations-min=1 \
-            -p no:sugar \
-            tests/components/${{ matrix.partial_group }}
       - name: Run pytest (fully)
         if: needs.info.outputs.test_full_suite == 'true'
         timeout-minutes: 60
